//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdToClasses tool.
//     Tool Version:    1.2.23.0
//     Runtime Version: 4.0.30319.269
//     Generated on:    15/08/2012 20:57:39
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace MissingPoster {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/WantedData")]
    [System.Xml.Serialization.XmlRootAttribute("WantedData", Namespace="http://BlueToque.ca/WantedData", IsNullable=false)]
    public partial class WantedDataType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string createdByField;
        
        /// <remarks/>
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <summary />
        private System.DateTime createdField;
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <summary />
        private string modifiedByField;
        
        /// <remarks/>
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <summary />
        private System.Nullable<System.DateTime> modifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
                this.RaisePropertyChanged("Modified");
            }
        }
        
        /// <summary />
        private string taskNumberField;
        
        /// <remarks/>
        public string TaskNumber {
            get {
                return this.taskNumberField;
            }
            set {
                this.taskNumberField = value;
                this.RaisePropertyChanged("TaskNumber");
            }
        }
        
        /// <summary />
        private string taskNameField;
        
        /// <remarks/>
        public string TaskName {
            get {
                return this.taskNameField;
            }
            set {
                this.taskNameField = value;
                this.RaisePropertyChanged("TaskName");
            }
        }
        
        /// <summary />
        private string firstNameField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <summary />
        private string lastNameField;
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <summary />
        private uint ageField;
        
        /// <remarks/>
        public uint Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("Age");
            }
        }
        
        /// <summary />
        private string heightStringField;
        
        /// <remarks/>
        public string HeightString {
            get {
                return this.heightStringField;
            }
            set {
                this.heightStringField = value;
                this.RaisePropertyChanged("HeightString");
            }
        }
        
        /// <summary />
        private string weightStringField;
        
        /// <remarks/>
        public string WeightString {
            get {
                return this.weightStringField;
            }
            set {
                this.weightStringField = value;
                this.RaisePropertyChanged("WeightString");
            }
        }
        
        /// <summary />
        private HeightType heightField;
        
        /// <remarks/>
        public HeightType Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("Height");
            }
        }
        
        /// <summary />
        private WeightType weightField;
        
        /// <remarks/>
        public WeightType Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("Weight");
            }
        }
        
        /// <summary />
        private SexType sexField;
        
        /// <remarks/>
        public SexType Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("Sex");
            }
        }
        
        /// <summary />
        private bool sexFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SexSpecified {
            get {
                return this.sexFieldSpecified;
            }
            set {
                this.sexFieldSpecified = value;
                this.RaisePropertyChanged("SexSpecified");
            }
        }
        
        /// <summary />
        private string complexionField;
        
        /// <remarks/>
        public string Complexion {
            get {
                return this.complexionField;
            }
            set {
                this.complexionField = value;
                this.RaisePropertyChanged("Complexion");
            }
        }
        
        /// <summary />
        private string clothingField;
        
        /// <remarks/>
        public string Clothing {
            get {
                return this.clothingField;
            }
            set {
                this.clothingField = value;
                this.RaisePropertyChanged("Clothing");
            }
        }
        
        /// <summary />
        private string sMTField;
        
        /// <remarks/>
        public string SMT {
            get {
                return this.sMTField;
            }
            set {
                this.sMTField = value;
                this.RaisePropertyChanged("SMT");
            }
        }
        
        /// <summary />
        private string healthField;
        
        /// <remarks/>
        public string Health {
            get {
                return this.healthField;
            }
            set {
                this.healthField = value;
                this.RaisePropertyChanged("Health");
            }
        }
        
        /// <summary />
        private string descriptionField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <summary />
        private ImageType imageField;
        
        /// <remarks/>
        public ImageType Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("Image");
            }
        }
        
        /// <summary />
        private string pointLastSeenField;
        
        /// <remarks/>
        public string PointLastSeen {
            get {
                return this.pointLastSeenField;
            }
            set {
                this.pointLastSeenField = value;
                this.RaisePropertyChanged("PointLastSeen");
            }
        }
        
        /// <summary />
        private string commentField;
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <summary />
        private ContactType contactField;
        
        /// <remarks/>
        public ContactType Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("Contact");
            }
        }
        
        /// <summary />
        private HeaderType headerField;
        
        /// <remarks/>
        public HeaderType Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        /// <summary />
        private FooterType footerField;
        
        /// <remarks/>
        public FooterType Footer {
            get {
                return this.footerField;
            }
            set {
                this.footerField = value;
                this.RaisePropertyChanged("Footer");
            }
        }
        
        /// <summary />
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <summary />
        private System.DateTime dOBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
                this.RaisePropertyChanged("DOB");
            }
        }
        
        /// <summary />
        private bool dOBFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DOBSpecified {
            get {
                return this.dOBFieldSpecified;
            }
            set {
                this.dOBFieldSpecified = value;
                this.RaisePropertyChanged("DOBSpecified");
            }
        }
        
        /// <summary />
        private System.DateTime taskDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime TaskDate {
            get {
                return this.taskDateField;
            }
            set {
                this.taskDateField = value;
                this.RaisePropertyChanged("TaskDate");
            }
        }
        
        /// <summary />
        private bool taskDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaskDateSpecified {
            get {
                return this.taskDateFieldSpecified;
            }
            set {
                this.taskDateFieldSpecified = value;
                this.RaisePropertyChanged("TaskDateSpecified");
            }
        }
        
        /// <summary />
        private System.DateTime dateLastSeenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime DateLastSeen {
            get {
                return this.dateLastSeenField;
            }
            set {
                this.dateLastSeenField = value;
                this.RaisePropertyChanged("DateLastSeen");
            }
        }
        
        /// <summary />
        private bool dateLastSeenFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateLastSeenSpecified {
            get {
                return this.dateLastSeenFieldSpecified;
            }
            set {
                this.dateLastSeenFieldSpecified = value;
                this.RaisePropertyChanged("DateLastSeenSpecified");
            }
        }
        
        /// <summary />
        private System.DateTime timeLastSeenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
        public System.DateTime TimeLastSeen {
            get {
                return this.timeLastSeenField;
            }
            set {
                this.timeLastSeenField = value;
                this.RaisePropertyChanged("TimeLastSeen");
            }
        }
        
        /// <summary />
        private bool timeLastSeenFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeLastSeenSpecified {
            get {
                return this.timeLastSeenFieldSpecified;
            }
            set {
                this.timeLastSeenFieldSpecified = value;
                this.RaisePropertyChanged("TimeLastSeenSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/WantedData")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://BlueToque.ca/WantedData", IsNullable=true)]
    public partial class HeightType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <summary />
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
                this.RaisePropertyChanged("ValueSpecified");
            }
        }
        
        /// <summary />
        private LengthUnits unitsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LengthUnits Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
                this.RaisePropertyChanged("Units");
            }
        }
        
        /// <summary />
        private bool unitsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitsSpecified {
            get {
                return this.unitsFieldSpecified;
            }
            set {
                this.unitsFieldSpecified = value;
                this.RaisePropertyChanged("UnitsSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/WantedData")]
    public enum LengthUnits {
        
        /// <remarks/>
        Feet,
        
        /// <remarks/>
        Metres,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/WantedData")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://BlueToque.ca/WantedData", IsNullable=true)]
    public partial class WeightType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <summary />
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
                this.RaisePropertyChanged("ValueSpecified");
            }
        }
        
        /// <summary />
        private WeightUnits unitsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public WeightUnits Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
                this.RaisePropertyChanged("Units");
            }
        }
        
        /// <summary />
        private bool unitsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitsSpecified {
            get {
                return this.unitsFieldSpecified;
            }
            set {
                this.unitsFieldSpecified = value;
                this.RaisePropertyChanged("UnitsSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/WantedData")]
    public enum WeightUnits {
        
        /// <remarks/>
        Pounds,
        
        /// <remarks/>
        Kilograms,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/WantedData")]
    public enum SexType {
        
        /// <remarks/>
        Female,
        
        /// <remarks/>
        Male,
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        Blank,
    }
}
#pragma warning restore 1591